[package]
name = "parsely"
version = "0.1.0"
entrypoint = "src/exports.typ"
authors = ["Joseph Wilson (Jollywatt)"]
license = "MIT"
description = "Parse equations and content into expression trees."
repository = "https://github.com/Jollywatt/typst-parsely"
exclude = [
	"docs/",
	"tests/",
	"scripts/",
]
categories = [
	"scripting",
	"utility",
]
keywords = [
	"parse",
	"parser",
	"tree",
	"syntax",
	"expression",
	"equation",
	"eval",
]
