[workspace]
channels = ["conda-forge"]
name = "scripts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
tomli = ">=2.4.0,<3"

[pypi-dependencies]
tree-sitter-rust = ">=0.24.0, <0.25"
tree-sitter = ">=0.25.2, <0.26"
